# Création du workflow personnalisé pour gradle dans le répertoire Backend.
name: Java CI with Gradle

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 17
      uses: actions/setup-java@v2
      with:
        java-version: '17'
        distribution: 'adopt'
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
      working-directory: ./Backend
    - name: Build with Gradle
      run: ./gradlew build
      working-directory: ./Backend
    - name: Test with Gradle
      run: ./gradlew test
      working-directory: ./Backend
    - name: Archive production artifacts
      uses: actions/upload-artifact@v2
      with:
        name: build-artifacts
        path: |
          ./Backend/build/libs/*.jar
          ./Backend/build/reports/tests/test/index.html